export default function DashboardPage() {
  const attendanceBars = [65, 70, 62, 75, 79, 73, 68, 84, 78, 90, 82, 88];
  const perfLine = [68, 71, 73, 76, 78, 80, 81, 84, 86, 85, 87];
  return (<>
    <div className="welcome-row"><div className="welcome-avatar">DN</div><div><h2>Welcome, HR Name 1</h2><p>HR Manager · Thu May 21 2026</p></div></div>
    <div className="metric-grid">{[['Total Employees','','650',''],['Upcoming Review','June','19','3 due in 7 days'],['Review Completed','May','10',''],['Under Review','May','26',''],['Review In Progress','May','16',''],['Appraisal Beneficiary','May','16','']].map(([label,month,value,warning]) => <div className="metric-card" key={label}><p className="mc-label">{label}</p>{month?<p className="mc-month">{month}</p>:null}<h3>{value}</h3><button type="button" className="btn btn-link p-0 mc-link">View Detail</button>{warning?<div className="mc-warning">⚠ {warning}</div>:null}</div>)}</div>
    <div className="chart-grid"><div className="chart-card"><h4>Employee allocation</h4><div className="donut-wrap"><div className="donut" /><ul><li><span className="dot d1" />IR (40%)</li><li><span className="dot d2" />TR (20%)</li><li><span className="dot d3" />IT (15%)</li><li><span className="dot d4" />HR (5%)</li><li><span className="dot d5" />Finance (10%)</li><li><span className="dot d6" />IT-Admin (10%)</li></ul></div></div>
    <div className="chart-card"><div className="d-flex justify-content-between align-items-center mb-3"><h4>Overall Employee Attendance</h4><select className="form-select form-select-sm w-auto"><option>2025–26</option></select></div><div className="chart-stat">91.4% <span>▲ +0.8% vs last year</span></div><p className="chart-sub">Min. threshold: 80% <span>(11 employees below threshold)</span></p><div className="bar-line">{attendanceBars.map((v,i)=><div key={`${v}-${i}`} style={{height:`${v}%`}} />)}</div><div className="months">{['J','F','M','A','M','J','J','A','S','O','N','D'].map((m)=><span key={m}>{m}</span>)}</div></div>
    <div className="chart-card"><div className="d-flex justify-content-between align-items-center mb-3"><h4>Overall Employee PA Performance</h4><select className="form-select form-select-sm w-auto"><option>2025–26</option></select></div><div className="chart-stat">88.3% <span>▲ +3.1% vs last year</span></div><p className="chart-sub">Target: 85% <span>(org avg above target)</span></p><svg viewBox="0 0 360 120" className="perf-svg"><line x1="0" y1="55" x2="360" y2="55" stroke="#e6a817" strokeDasharray="4 3" /><polyline points={perfLine.map((v,i)=>`${i*33},${110-v}`).join(' ')} fill="none" stroke="#2b8d72" strokeWidth="2" /></svg><div className="months">{['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov'].map((m)=><span key={m}>{m}</span>)}</div></div></div>
  </>);
}
