const masterRows = [
  ['100001','Employee Name 1','CBE','Internet Research','82%','95','Probation','-','20-Sep-2025','NA','-','NA'],
  ['100002','Employee Name 2','CBE','Information Technology','85%','91','Probation','-','28-Apr-2025','NA','-','NA'],
  ['100003','Employee Name 3','CBE','Internet Research','78%','88','Probation','TL Ranking','20-Apr-2026','NA','TL Ranking','Pending'],
  ['100004','Employee Name 4','CBE','Information Technology','90%','94','Annual','Settled','20-Mar-2026','20-Apr-2024','HR Review','Approved'],
  ['100005','Employee Name 5','CNR','Telephone Research','82%','87','Annual','Deferred','20-Jul-2025','20-Apr-2024','-','Extended'],
  ['100006','Employee Name 6','CBE','Finance','76%','80','Annual','Priority','20-Mar-2026','20-Apr-2024','-','Rejected'],
  ['100007','Employee Name 7','CR','Internet Research','88%','92','Annual','Priority','20-Mar-2026','20-Apr-2024','-','Rejected'],
  ['100008','Employee Name 8','PH','Information Technology','83%','89','Annual','Priority','20-Mar-2026','20-Apr-2024','-','Rejected']
];

export default function MasterListPage() {
  return (<div className="master-wrap"><div className="master-alert">ℹ Showing employees across all departments. Use filters to narrow by Appraisal Type, Department, or Review Status.</div><div className="master-card"><div className="master-filters"><input className="form-control" placeholder="Search by Name, ID, Department, Location..." /><select className="form-select"><option>All Departments</option></select><select className="form-select"><option>All Appraisal Types</option></select><select className="form-select"><option>All Locations</option></select><select className="form-select"><option>All Statuses</option></select><button className="btn btn-light">Filter ▾</button></div><div className="table-responsive"><table className="table master-table align-middle"><thead><tr><th></th><th>ID ↕</th><th>NAME ↕</th><th>LOCATION ↕</th><th>DEPARTMENT ↕</th><th>PA SCORE ↕</th><th>ATTENDANCE ↕</th><th>APPRAISAL TYPE ↕</th><th>RANKING ↕</th><th>NEXT REVIEW ↕</th><th>PREV REVIEW ↕</th><th>REVIEW STAGE ↕</th><th>DISCUSSION STATUS ↕</th><th>VIEW DETAILS</th></tr></thead><tbody>{masterRows.map((r) => {const attendance = Number(r[5]); return <tr key={r[0]}><td><input type="checkbox" /></td><td>{r[0]}</td><td>{r[1]}</td><td>{r[2]}</td><td>{r[3]}</td><td>{r[4]}</td><td><div className="att-cell"><span>{r[5]}%</span><div className="att-track"><div className="att-fill" style={{ width: `${attendance}%` }} /></div></div></td><td><span className={`pill ${r[6] === 'Annual' ? 'amber' : 'blue'}`}>{r[6]}</span></td><td><span className={`rank ${r[7].toLowerCase()}`}>{r[7]}</span></td><td>{r[8]}</td><td>{r[9]}</td><td><span className="pill gray">{r[10]}</span></td><td><span className={`pill ${r[11] === 'Approved' ? 'green' : r[11] === 'Extended' ? 'amber' : r[11] === 'Rejected' ? 'red' : 'gray'}`}>{r[11]}</span></td><td><button className="btn btn-sm btn-outline-secondary">View</button></td></tr>;})}</tbody></table></div><div className="master-footer"><span>1-50 of 1500 Employees</span><span>Rows per Page 50 · Page 1 / 4</span></div></div></div>);
}
